rtls_server/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include(('webapp.urls', 'webapp'), namespace='webapp')),
    path('admin/', admin.site.urls),
]

webapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('mainline', views.mainline, name='mainline'),
    path('clinic', views.clinic, name='clinic'),
    path('manager', views.manager, name='manager'),
    path('executive', views.executive, name='executive'),
    path('ie', views.ie, name='ie'),
    path('tagAssign', views.tagAssign, name = 'tagAssign'),
    path('insert_tagAssign', views.insert_tagAssign, name = 'insert_tagAssign'),
    path('data', views.data, name='data'), # used for returning metrics and other data via AJAX requests on the browser side
    path('updateClinicTable', views.update_clinic_table, name='updateClinicTable')
]

webapp/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

# Create your models here.
class DataPoint(models.Model):
    tag_id = models.CharField(max_length=150)
    timestamp = models.DateTimeField()
    zone = ArrayField(models.CharField(max_length=150, null=True))
    x_pos = models.DecimalField(decimal_places=2, max_digits=4)
    y_pos = models.DecimalField(decimal_places=2, max_digits=4)
    button_pushed = models.BooleanField()

    def __str__(self):
        return "Tag %s at %s" % (self.tag_id, self.timestamp)

class Tag(models.Model):
    tag_id = models.CharField(max_length=50)
    tag_name = models.CharField(max_length=150)
    serial_num = models.CharField(max_length=150)
    valid_after = models.DateTimeField()
    valid_before = models.DateTimeField(null=True)

    def __str__(self):
        return "Tag %s, serial number %s" % (self.tag_id, self.serial_num)

class ClinicItem(models.Model):
    tag_id = models.CharField(max_length=150)
    serial_num = models.CharField(max_length=150)
    added_to_clinic = models.DateTimeField()
    removed_from_clinic = models.DateTimeField(null=True)
    from_zone = ArrayField(models.CharField(max_length=150))
    problem = models.CharField(max_length=1000)

    def __str__(self):
        return "Tag %s, serial number %s" % (self.tag_id, self.serial_num)

webapp/views.py
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponseServerError
from django.shortcuts import render, redirect
from django.urls import reverse
from django.conf import settings
from django.forms.models import model_to_dict

from .models import DataPoint, Tag, ClinicItem

import datetime

# Mainline Page
def mainline(request):
    context = {
        "workstations": [
            "Workstation 1A",
            "Workstation 1B",
            "Workstation 2",
            "Rework",
        ],
        "move_transactions": [
            {
                "name": "Tag 1",
                "approve_link": "#",
                "deny_link": "#",
            },
            {
                "name": "Tag 2",
                "approve_link": "#",
                "deny_link": "#",
            },
            {
                "name": "Tag 3",
                "approve_link": "#",
                "deny_link": "#",
            },
        ],
        "metrics": {
            "daily_pace_percent": "85",
            "units_sent_to_clinic": '',
            "yield": "80%",
        },
        "units_present": [
            {
                "serial": "00052",
                "tag_id": 1
            },
            {
                "serial": "00056",
                "tag_id": 14
            },
            {
                "serial": "00054",
                "tag_id": 33
            }
        ]
    }
    return render(request, 'webapp/mainline.html', context)

# Homepage
def index(request):
    return redirect(reverse('webapp:mainline'))

# Clinic Page
def clinic(request):
    context = {
        "clinic_items": [],
    }
    clinic_items = ClinicItem.objects.all()
    for item in clinic_items:
       context["clinic_items"].append(item)
        
    return render(request, 'webapp/clinic.html', context)

# Manager Page
def manager(request):
    return render(request, 'webapp/manager.html')

# Executive Page
def executive(request):
    context = {
        "metrics": {
            "avg_time_prob_solution": "8.2 hrs",
            "prob_freq": "2%",
            "on_time_delivery": "85%",
            "perc_on_takt" : "71%"
        }
    }
    return render(request, 'webapp/executive.html', context)

# IE/CI Page
def ie(request):
    context = {
        "metrics": {
            "daily_pace_percent": "85",
            "units_sent_to_clinic": 5,
            "yield": "80%",
            "on_time_delivery": "85%",
            "perc_on_takt" : "71%"
        }
    }
    return render(request, 'webapp/ie.html', context)

# Tag Assignment Page
def tagAssign(request):
    tag_objects = Tag.objects.all()
    context_tag = {
        "tag_point_objects": tag_objects,
        "tags_hardcode" :[
            {
                "serial": "00052",
                "tag_id": 1
            },
            {
                "serial": "00056",
                "tag_id": 14
            },
            {
                "serial": "00054",
                "tag_id": 33
            }
        ]
    }
    return render(request, 'webapp/tagAssign.html', context_tag)

# Tag Assignment Updater
def insert_tagAssign(request):
    newTag = Tag(tag_id = request.POST['tagID_TB'], tag_name = request.POST['tagName_TB'], serial_num = request.POST['SN_TB'], valid_after = request.POST['time_TB'])
    #content = request.POST['tagID_TB', 'SN_TB', 'time_TB']
    #newTag = Tag(content)
    newTag.save()
    return redirect('/tagAssign')
    #return render(request, 'webapp/manager.html')

# Clinic Table Updater
def update_clinic_table(request):
    operation = request.POST['operation'] if request.POST['operation'] else None

    if operation == None:
        return HttpResponseBadRequest("Missing 'operation' parameter")

    if operation == "add":
        try:
            serial_num = request.POST['serial_num']
            from_zone = request.POST['workstation']
            problem = request.POST['problem']
        except AttributeError:
            return HttpResponseBadRequest("Missing parameter")

        # Get tag id corresponding with submitted serial number (works similarly to add_serial_numbers() below)
        try:
            tag_id = Tag.objects.filter(
                valid_after__lte = datetime.datetime.now(),
                #valid_before__gte = datetime.datetime.now(), # Commented out for demo because the query returns nothing when valid_before is null.
                serial_num = serial_num,
            ).first().tag_id
        except AttributeError:
            return HttpResponseServerError("No tag assigned to serial number %s" % serial_num)

        # Create new table row
        clinic_item = ClinicItem(
            tag_id = tag_id,
            serial_num = serial_num,
            added_to_clinic = datetime.datetime.now(),
            from_zone = [from_zone], # from_zone in models.py is an ArrayField, so we have to pass an array
            problem = problem,
        )
        clinic_item.save()
    
    return JsonResponse({
        'data': {
            'message': 'Serial number %s successfully added to clinic.' % clinic_item.serial_num,
        }
    })

# Returns JSON-formatted request_types and other data in response to AJAX requests
def data(request):
    # Determine which workstation we're talking about, if any
    workstation = request.GET['workstation'] if 'workstation' in request.GET else None

    # Determine what data we want to get
    request_type = request.GET['request_type'] if 'request_type' in request.GET else None

    # If no request_type provided, abort
    if request_type == None:
        return HttpResponseBadRequest("Missing 'request_type' parameter")

    # Workstation-related queries
    if workstation:
        # Units Present
        if request_type == "units_present":
            oldest_valid_timestamp = datetime.datetime.now() - datetime.timedelta(seconds=settings.CURRENT_POSITION_LOOKBACK)
            units = DataPoint.objects.filter(
                timestamp__gte = oldest_valid_timestamp,    # find all datapoints with timestamp greater than or equal to the current time minus CURRENT_POSITION_LOOKBACK seconds
                zone__contains = [workstation]              # find the subset that are flagged with the workstation of interest (using list() to avoid syntax errors in Postgres)
            )

            units = add_serial_numbers(units, 'tag_id')

            return JsonResponse({'data': units})

        # Units sent to clinic from workstation in past x hours
        if request_type == "units_sent_to_clinic":
            hours_ago = request.GET['hours_ago']
            oldest_valid_timestamp = datetime.datetime.now() - datetime.timedelta(hours=int(hours_ago))
            units = ClinicItem.objects.filter(
                from_zone__contains = [workstation],
                added_to_clinic__gte = oldest_valid_timestamp
            )

            return JsonResponse({'data': len(units.values())})
    
    # Non-workstation-related queries
    else:
        # Map data
        if request_type == 'map_data':
            oldest_valid_timestamp = datetime.datetime.now() - datetime.timedelta(seconds=settings.CURRENT_POSITION_LOOKBACK)
            data = DataPoint.objects.filter(
                timestamp__gte = oldest_valid_timestamp,
            ).order_by(
                "-timestamp" # put the most recent data on top
            )

            data = add_serial_numbers(data, 'tag_id', 'x_pos', 'y_pos', 'button_pushed')

            return JsonResponse({'data': data})

    # If nothing matched, abort
    return HttpResponseBadRequest("Invalid request")

# Helper function to match serial numbers and tags
def add_serial_numbers(units, *columns_to_keep):
    # Find the related serial number for each tag_id in the retrieved dataset. Must be current.
    serial_nums = []
    for unit in units:
        tag_assignment = Tag.objects.filter(
            #valid_after__lte = unit.timestamp,
            #valid_before__gte = unit.timestamp,
            tag_id = unit.tag_id
        )
        try:
            serial_nums.append(tag_assignment.first().serial_num)
        except AttributeError:
            # If the tag doesn't have a valid serial number match, insert a string that says so
            serial_nums.append('S/N not found')
            continue
    
    # Merge serial numbers into list of present units
    units = list(units.values(*columns_to_keep))
    for i in range(len(serial_nums)):
        units[i]['serial_num'] = serial_nums[i]

    return units

webapp/templates/webapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        {% block head %}
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <title>{% block title %}Quuppa RTLS{% endblock title %}</title>
        <link rel="icon" type="image/png" href="{% static 'webapp/favicon.ico' %}" />
        {% endblock head %}
    </head>
    <body>
        <div class="container">
            {% block navbar %}
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                  <a class="navbar-brand" href="/">Quuppa RTLS</a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'mainline' %}active{% endif %}" href="{% url 'webapp:mainline' %}">Mainline</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'clinic' %}active{% endif %}" href="{% url 'webapp:clinic' %}">Clinic</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'manager' %}active{% endif %}" href="{% url 'webapp:manager' %}">Manager</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'executive' %}active{% endif %}" href="{% url 'webapp:executive' %}">Executive</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'ie' %}active{% endif %}" href="{% url 'webapp:ie' %}">IE & CI</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'tagAssign' %}active{% endif %}" href="{% url 'webapp:tagAssign' %}">Tag Assignment</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </nav>
            {% endblock navbar %}
            {% block content %}
            <p>Hello world! This is the base template. Override the 'content' block to put something more interesting here.</p>
            {% endblock content %}
        </div>

        <!-- jQuery -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

        <!-- Bootstrap -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
        {% block scripts %}

        <!-- Chart.JS -->
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        {% endblock scripts %}
    </body>
</html>

webapp/templates/webapp/clinic.html
{% extends 'webapp/base.html' %}
{% load static %}

{% block content %}
<div class="table-responsive">
    <table id = 'clinic-table' class="table table-striped table-sm table-bordered my-3">
        <thead>
        <tr>
            <th class="text-center" colspan="8">Nonconforming Material</th>
        </tr>
        <tr>
            <th style="width:20%">Tag ID</th>
            <th style="width:20%">Date/Time Entered</th>
            <th style="width:20%">Origin Workstation</th>
            <th style="width:40%">Nonconforming Description</th>
            <th style="width:20%">Date/Time Resolved</th>
            <th style="width:20%">Resolved</th>
        </tr>
        </thead>
        <tbody>
        {% for item in clinic_items %}
        <tr>
            <td id='tag_id'>{{ item.tag_id }}</td>
            <td id = 'date/time entered'>{{ item.added_to_clinic }}</td>
            <td id = 'workstation'>{{ item.from_zone.0 }}</td>
            <td id = 'description'>{{ item.problem }}</td>
            <td id = 'date/time resolved'>{{ item.removed_from_clinic }}</td>
            <td id = 'delete_row'>
                <button type ="button" class ="btn btn-sm btn-success">Resolve</button>
            </td>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>


</div>
{% endblock content %}

webapp/templates/webapp/executive.html
{% extends 'webapp/base.html' %}
{% load static %}

{% block content %}


<div class="row">
  <!--Yield Graph-->
  <div class="col-8">
      <canvas id = "myYieldChart" height = "70%"></canvas>
  </div>
  <!-- Timeframe selector -->
  <div class="col-4">
    <form>
      <div class="form-group">
        <label for="workstation">Pick a timeframe:</label>
        <select class="form-control" id="timeframe">
          <option value="1day">Day</option>
          <option value="1week">Week</option>
          <option value="1month">Month</option>
          <option value="1year">Year</option>
        </select>
      </div>
    </form>
  <!-- % Time on Takt Scorecard % -->
  <div class="row">
    <div class="col-6">
      <div class="card mb-2">
        <div class="card-body">
          <h6 class="card-title text-center"> % Time on Takt</h6>
          <p class="card-text text-center fs-1">{{ metrics.perc_on_takt }}</p>
        </div>
      </div>
    </div> 
    <!-- % Average Time to Solve Problem Scorecard % -->
    <div class="col-6">  
      <div class="card mb-2">
        <div class="card-body">
          <h6 class="card-title text-center">On-Time Delivery</h6>
          <p class="card-text text-center fs-1">{{ metrics.on_time_delivery }}</p>
        </div>
      </div>
    </div>
  </div>
</div>

<!--Cost Graph and Lead Time Table-->
<div class="row">
  <div class="col-8">
    <canvas id = "myCostChart" height = "70%"></canvas>
  </div>
  <div class="col-4">
    <table class="table table-striped table-sm table-bordered my-3">
        <thead>
          <tr>
            <th class="text-center" colspan="3">Lead Time</th>
          </tr>
            <tr>
              <th style="width:60%">Serial Number</th>
              <th style="width:40%" colspan="2">Time(days)</th>
            </tr>
        </thead>
    </table>    
  </div>                
</div>  

<!-- % Problem Frequency Scorecard % -->
<div class="row">
  <div class="col-4">
    <div class="card mb-2">
        <div class="card-body">
            <h6 class="card-title text-center"> Problem Frequency</h6>
            <p class="card-text text-center fs-1">{{ metrics.prob_freq }}</p>
        </div>
    </div>
  </div> 
<!-- % Average Time to Solve Problem Scorecard % -->
  <div class="col-4">
    <div class="card mb-2">
        <div class="card-body">
            <h6 class="card-title text-center">Average Time to Solve Problem</h6>
            <p class="card-text text-center fs-1">{{ metrics.avg_time_prob_solution }}</p>
        </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block scripts %}
  {{ block.super }}
  <script type="text/javascript">
    const yieldLabels = ["Jan", "Feb", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
    const yieldData = {
      labels: yieldLabels,
      datasets: [{
      data: [75, 76, 80, 81, 85, 85, 86, 82, 80, 75, 80, 81],
      fill: false,
      borderColor: 'rgb(0, 0, 0)',
      tension: 0.1
}]
};
    const yieldConfig = {
      type: 'line',
      data: yieldData,
      options: {
        plugins: {
          legend: {
            display: false
          },
            title: {
              display: true,
              text: 'Yield Overtime',
              font: {
                size: 20
              }
            }
        }
      } 
};

    const costLabels = ["Jan", "Feb", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
      const costData = {
        labels: costLabels,
        datasets: [{
          data: [10000, 10500, 9900, 11000, 9000, 9300, 9500, 9300, 9000, 9400, 8900, 9100],
          fill: false,
          borderColor: 'rgb(0, 0, 0)',
          tension: 0.1
        }]
      };
    const costConfig = {
      type: 'line',
      data: costData,
      options: {
        plugins: {
          legend: {
            display: false
          },
            title: {
                display: true,
                text: 'Cost Overtime',
                font: {
                  size: 20
                }
            }
        }
      }    
};

var YieldChart = new Chart(document.getElementById("myYieldChart"), yieldConfig);
var CostChart = new Chart(document.getElementById("myCostChart"), costConfig);

    </script>


      <!--function updateUnitsSentToClinic() {
        $.ajax({
            url: "{% url 'webapp:data' %}",
            data: {
                'request_type': 'units_sent_to_clinic',
                'workstation': 'Workstation 2',
                'hours_ago': 8
            },
            success: (response) => {
                // Clear out old data
                map.data.datasets[0].data = [];

                // Feed in new map data
                for (var i in response.data) {
                    map.data.datasets[0].data.push({
                        'x': response.data[i]['x_pos'],
                        'y': response.data[i]['y_pos']
                    })
                }

                map.update();
            }
        });
      }

      function updatePercentTimeOnTakt() {
        $.ajax({
          url: "{% url 'webapp:data' %}",
          data: {
            'request_type': 'percent_time_on_takt',
            'timeframe': $("#timeframe").val()
          },
          success: function(response) {
            alert(response);
          }
        });
      }

      document.getElementById("timeframe").addEventListener('change', function(event) {
        updatePercentTimeOnTakt();
      });

      </script>
-->
{% endblock scripts %}

webapp/templates/webapp/index.html
{% extends 'webapp/base.html' %}
{% block content %}
    <h1>Hello world! This is the index template. Testing 1 2 3</h1>
{% endblock content %}

webapp/templates/webapp/manager.html
{% extends 'webapp/base.html' %}
{% load static %}

{% block head %}
{{ block.super }}
<style>
    #myChart {
        background-image: url('{% static 'webapp/chart_bg.png' %}');
        background-size: 100%;
    }
</style>
{% endblock head %}



{% block content %}
    <h1>Manager</h1>
    <div class="container">
        <div class="row">
            <div class = "col-5">
                <canvas id= "myChart"></canvas>
            </div>
            <div class = "col-4">
                <canvas id="barChart"></canvas>
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <div class="card pb-3">
                    <div class="card-body">
                        <h4 class="card-title text-center">Process Time</h4>
                    </div>
                    <canvas id="process_time_canvas"></canvas>
                </div>  
            </div>
            <div class="col-3">
                <div class="card pb-3">
                    <div class="card-body">
                        <h4 class="card-title text-center">Queue Time</h4>
                    </div>
                    <canvas id="queue_time_canvas"></canvas>
                </div>
            </div>
            <div class="col-3">
                <div class="card pb-3">
                    <div class="card-body">
                        <h4 class="card-title text-center">Cycle Time</h4>
                    </div>
                    <canvas id="cycle_time_canvas"></canvas>
            </div>
            
        </div>
    </div>
    </div>
    {% comment %} <span id="clock"></span> {% endcomment %}
</div>


{% endblock content %}




{% block scripts %}
    {{ block.super }}
<!-- Map and graph code -->
    <script type="text/javascript">
        const labels = [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        ];
        const data = {
            datasets: [{
                label: 'Tag Positions',
                backgroundColor: 'rgb(255, 99, 132)',
                borderColor: 'rgb(255, 99, 132)',
                data: [{
                    x: -10,
                    y: 0
                  }, {
                    x: 0,
                    y: 10
                  }, {
                    x: 10,
                    y: 5
                  }, {
                    x: 0.5,
                    y: 5.5
                }],
            }]
        };
        var config = {
            type: 'scatter',
            data: data,
            options: {
                elements : {
                    point: {
                        radius: 10,
                    }
                },
                plugins: {
                    legend: {
                        display: false
                    }
                },
                scales: {
                   x: {
                        display: false,
                        type: 'linear',
                        position: 'bottom',
                        min: -7.92,
                        max: 6.28
                    },
                    y: {
                        display: false,
                        type: 'linear',
                        position: 'left',
                        min: -3.17,
                        max: 4.39
                    }
                }
            }
        };

        var map = new Chart(
            document.getElementById('myChart'),
            config
        );

        // ********** AJAX UPDATERS *********** //

        // Map
        function updateMap() {
            $.ajax({
                url: "{% url 'webapp:data' %}",
                data: {
                    'request_type': 'map_data',
                },
                success: (response) => {
                    // Clear out old data
                    map.data.datasets[0].data = [];

                    // Feed in new map data
                    for (var i in response.data) {
                        map.data.datasets[0].data.push({
                            'x': response.data[i]['x_pos'],
                            'y': response.data[i]['y_pos']
                        })
                    }

                    map.update();
                }
            });
        }

        // Start running the updaters
        $(document).ready(() => {
            setInterval(updateMap, 125);
        });



        //bar chart
        var config = {
            type: 'scatter',
            data: data,
            options: {
                scales: {
                y: {
                    beginAtZero: true
                }
                }
            }
        };
        var mixedChart = new Chart(
            document.getElementById('barChart'), {
            type: 'bar',
            data: {
                datasets: [{
                    label: 'Occurances',
                    data: [15, 10, 5, 2],
                    // this dataset is drawn below
                    yAxisID: 'leftAxis',
                    order: 2
                }, {
                    label: 'Cumulative Percentage',
                    data: [15/32, 25/32, 30/32, 32/32],
                    type: 'line',
                    borderColor: 'rgb(54, 162, 235)',
                    backgroundColor: 'rgb(54, 162, 235)',
                    // this dataset is drawn on top
                    yAxisID: 'rightAxis',
                    order: 1
                }],
                labels: ['Software Error', 'Physical Defect', 'Op. Error', 'Misc.']
            },
            options: {
                scales: {
                    /*
                    y: {
                    beginAtZero: true
                    }
                    */
                    leftAxis: {
                        id: 'A',
                        type: 'linear',
                        position: 'left',
                    },
                    rightAxis: {
                        id: 'B',
                        type: 'linear',
                        position: 'right',
                        //ticks: {
                          //  max: 1,
                            //min: 0
                        //}
                    }
                }
            }
        });


    </script>

<script src="https://bernii.github.io/gauge.js/dist/gauge.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<!-- Gauges code -->
<script type="text/javascript">
    var opts = {
        angle: 0, // The span of the gauge arc
        lineWidth: 0.2, // The line thickness
        radiusScale: 1, // Relative radius
        pointer: {
            length: 0.6, // // Relative to gauge radius
            strokeWidth: 0.035, // The thickness
            color: '#000000' // Fill color
        },
        limitMax: 0,     // If false, max value increases automatically if value > maxValue
        limitMin: 100,     // If true, the min value of the gauge will be fixed
        colorStart: '#6F6EA0',   // Colors
        colorStop: '#C0C0DB',    // just experiment with them
        strokeColor: '#EEEEEE',  // to see which ones work best for you
        generateGradient: true,
        highDpiSupport: true,     // High resolution support
        staticZones: [
            {strokeStyle: "#F03E3E", min: 0, max: 30}, // Red from 100 to 130
            {strokeStyle: "#FFDD00", min: 30, max: 60}, // Yellow
            {strokeStyle: "#198754", min: 60, max: 100}, // Green
        ],
        staticLabels: {
            font: "15px sans-serif",  // Specifies font
            labels: [0, 30, 60, 100],  // Print labels at these values
            color: "#000000",  // Optional: Label text color
            fractionDigits: 0  // Optional: Numerical precision. 0=round off.
        }
    };
    
    
    /*
    var gaugeLimits = {
        maximum: 150,
        minimum: 0,
        redPercent: .3,
        yellowPercent: .3
    };

    opts.limitMax = gaugeLimits.maximum;
    opts.limitMin = gaugeLimits.minimum;
    opts.staticZones[0].max = (gaugeLimits.maximum*gaugeLimits.redPercent);
    opts.staticZones[1].min = (gaugeLimits.maximum*gaugeLimits.redPercent);
    opts.staticZones[1].max = (gaugeLimits.maximum*gaugeLimits.redPercent)+(gaugeLimits.maximum*gaugeLimits.yellowPercent);
    opts.staticZones[2].min = (gaugeLimits.maximum*gaugeLimits.redPercent)+(gaugeLimits.maximum*gaugeLimits.yellowPercent);
    opts.staticZones[2].max = gaugeLimits.maximum;
    
    var optsCopy =opts;
    */
    var target = document.getElementById("process_time_canvas");
    var gauge = new Gauge(target).setOptions(opts);
    gauge.setMinValue(0);
    gauge.maxValue = 100;
    gauge.set(70);

    /* Trying some things out
    var tempColor = opts.colorStart;
    opts.colorStart = opts.colorStop;
    opts.colorStop = tempColor;
    //opts.angle = -.01;
    */
    

    var target = document.getElementById("queue_time_canvas");
    var gauge = new Gauge(target).setOptions(opts);
    gauge.setMinValue(0);
    gauge.maxValue = 100;
    gauge.set(40);


    var target = document.getElementById("cycle_time_canvas");
    var gauge = new Gauge(target).setOptions(opts);
    gauge.setMinValue(0);
    gauge.maxValue = 100;
    gauge.set(70);


    incElement = document.getElementById("cycle_time_canvas");
    // function increaseGauge(){
    //     incElement.set()
    // }
</script>

<!-- Just messing with live updates-->
<script type="text/javascript">
    var clockElement = document.getElementById('clock');

    function clock() {
        clockElement.textContent = new Date().toString();
    }

    setInterval(clock, 1000);
</script>

{% endblock scripts %}